<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net480</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bonsai.Core" Version="2.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="AllenNeuralDynamics.AindBehaviorServices" Version="0.13.4" />
    <PackageReference Include="AllenNeuralDynamics.AindBehaviorServices.Distributions" Version="0.2.0" />
    <PackageReference Include="Bonsai.ImPlot" Version="0.2.0" />
    <PackageReference Include="Bonsai.Harp" Version="3.6.1" />
    <PackageReference Include="Bonsai.ImGui.Visualizers" Version="0.2.0" />
    <PackageReference Include="Rx-Core" Version="2.2.5" />
    <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageReference Include="Hexa.NET.ImPlot" Version="2.2.9" />
    <PackageReference Include="MathNet.Numerics" Version="4.15.0" />
    <PackageReference Include="System.Collections.Immutable" Version="10.0.11" />
  </ItemGroup>
</Project>